[package]
name = "HomeAutomation"
version = "0.1.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]
edition = "2018"

[features]
default = []

# Enable code that expects sensor hardware to be present. Will stop execution
# if hardware is not present,
# on by default for testing use cargo flag: --no-default-features
sensors_connected = []
live_server = []

[dependencies]
actix-web = { version = "1.0.3", features = ["rust-tls"] }
actix-net = "0.2.4"
actix-identity = "0.1.0"
actix-files = "0.1.3"
actix-rt = "0.2.4"
actix-service = "0.4.1"
actix-web-httpauth = "0.3.2"
rustls = "0.15.2"

#philipshue = { git = "https://github.com/dskleingeld/philipshue", branch = "master" }
#for local dev purpose we use below targets
philipshue = { path = "../philipshue"}
secure-ble = { path = "../home_sensors/ble/central"}

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
log = "0.4"

#sysfs_gpio = { version = "0.5.3", features = ["use_tokio"] }
sysfs_gpio = { git = "https://github.com/rust-embedded/rust-sysfs-gpio", branch = "master", features = ["use_tokio"] }

tokio = "0.1.15"
futures = { version = "0.1"}
bincode = "1.0.1"
ring = "0.14.6"

linux-embedded-hal = "0.2.2"
bme280 = "0.1.1"

smallvec = "0.6.6"
chrono = { version = "0.4.6", features = ["serde"] }
bytes = "0.4.11"
byteorder = "1.3.1"

crossbeam-channel = "0.3"

sled = "0.24.1"
pagecache = "0.17.0"
reqwest = "0.9.17"

mpd = "0.0.12"
dirs = "2.0.1"
rand = "0.6"
retry = "0.5.1"
