[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["sensor-nodes/*"]

[workspace.dependencies]
data-server = { path = "crates/data-server" }
data-store = { path = "crates/data-store" }
protocol = { path = "crates/protocol" }

[workspace.package]
rust-version = "1.78"
edition = "2021"
license = "GPLv3"
authors = ["David Kleingeld & Eva van Houten"]

[profile.release]
debug = true
