[package]
name = "brain"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
protocol = { path = "../protocol" }
data-server = { path = "../data-server" }

futures = "0.3"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7.4", default-features = false, features = ["tokio", "http1"] }
axum-macros = "0.4.1"

philipshue = { git = "https://github.com/dvdsk/philipshue", branch = "master" }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
bincode = "1.3"

thiserror = "1.0"

chrono = { version = "0.4", features = ["serde"] }
time = { version = "0.3.36", features = ["macros"] }
tz-rs = "0.6.14"

bytes = "1.5"
byteorder = "1.4"

sled = "0.34"

mpd = "0.1"
rand = "0.8"

futures-util = "0.3.30"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-journald = "0.3.0"
log-panics = "2.1.0"
clap = { version = "4.5.4", features = ["derive"] }
futures-concurrency = "7.5.0"
strum = { version = "0.26.2", default-features = false, features = ["derive"] }
